language: r
r:
  - bioc-release

sudo: required
cran: https://cran.rstudio.com

cache:
  packages: true
apt_packages: libnetcdf-dev
r_github_packages: lgatto/MSnbase

env:
  global:
    - NOT_CRAN: true
    - R_CHECK_ARGS="--as-cran --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
